language: node_js
node_js:
  - 10
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/core.git iota-pico/core
  - cd iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/api.git iota-pico/api
  - cd iota-pico/api
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/data.git iota-pico/data
  - cd iota-pico/data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/crypto.git iota-pico/crypto
  - cd iota-pico/crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/business.git iota-pico/business
  - cd iota-pico/business
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto @iota-pico/api
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/pal-nodejs.git iota-pico/pal-nodejs
  - cd iota-pico/pal-nodejs
  - npm link @iota-pico/core
  - npm link
  - cd ../pow-srvio
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto @iota-pico/api @iota-pico/business @iota-pico/pal-nodejs
  - npm install
script:
  - npm run dist || travis_terminate 1
  - npm run test-publish || travis_terminate 1
cache:
  directories:
    - "node_modules"
